# Generated by Django 5.0.4 on 2024-06-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actividad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='lugar',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='dia',
        ),
    ]
