# Generated by Django 5.0.4 on 2024-06-18 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamientos', to='core.actividad'),
        ),
    ]
